### ISSUE TITLE
Parsing broken for campaignSubscriberActivity on the Export API

### ISSUE THREAD

**Issue by djhopper01** [envygeeks/ruby-feralchimp#14]
Thanks for the gem. We've been using it to build a deep integration with Mailchimp. Their v3 API isn't complete for our needs yet, so this has been a great help.

It seems like the campaignSubscriberActivity parsing is broken. The documentation states that the response will be text:
> a plain text dump of JSON objects. Each line/row returned is an individual JSON object.

This is what I'm getting returned:

```ruby
Feralchimp.new.export.campaignSubscriberActivity(id: "abcdefg123")

# It returns a Hash like this
{
  [ "john@example.com", [ { "action => "open", "timestamp" => "2016-01-06 22:08:45", "url" => nil, "ip" => "10.0.0.1" } ] ] => [
    "jim@example.com",
    [
      {
        "action" => "open",
        "timestamp" => "2016-01-06 22:08:45",
        "url" => nil,
        "ip" => "10.0.0.1"
      }, {
        "action" => "open",
        "timestamp" => "2016-01-06 22:08:45",
        "url" => nil,
        "ip" => "10.0.0.1"
      }
    ]
  ]
}
```

It looks like there are two email addresses for which there are events. This matches what I see on the Mailchimp UI for the campaign. However, the group of events for the first email address is the Hash key for the second group of events. Any ideas?

By the way, I don't think this is a huge issue because there are new options in the v3 API to retrieve this data. However, it does seem like it's broken unless we're missing something.

API Documentation: https://apidocs.mailchimp.com/export/1.0/campaignsubscriberactivity.func.php

**Comment by envygeeks** [comment]
I don't have the data you have (since we outgrew Mailchimp) but I definately still try to maintain this.  Is there any way you can run that API, mock out what it gives you so I can take that mock in our suite.

**Comment by djhopper01** [comment]
This is exactly what I get when calling their API directly. I avoided pretty formatting so you can see the exact response.

```
 {"john@example.com":[{"action":"open","timestamp":"2016-01-06 21:45:34","url":null,"ip":"10.0.0.1"},{"action":"click","timestamp":"2016-01-06 21:47:37","url":"https:\/\/google.com","ip":"10.0.0.1"}]}
{"jim@example.com":[{"action":"open","timestamp":"2016-01-06 22:08:45","url":null,"ip":"10.0.0.1"},{"action":"open","timestamp":"2016-01-06 22:18:29","url":null,"ip":"10.0.0.1"}]}

```

**Comment by envygeeks** [comment]
Great, since we are in a tight deadline for Jekyll and I have a lot of stuff I need to get out for it, I probably won't be able to get to this till this weekend but I'll make a spec out of your data and get it fixed for you this weekend if I can!

Thanks again.
